### PR TITLE
Improvements to the personal access token dialogs

### PR DESCRIPTION
**Pull request by eamansour**
For https://github.com/galasa-dev/projectmanagement/issues/1647

- Added a description to explain what a personal access token is and why users would want to create one
- Added an example placeholder to the "Token Name" field to give users a hint as to what they could name their token
- Link to Galasa docs now opens in a new tab to avoid losing the token dialog
- Added "in your Galasa home directory" in the token response dialog to clarify where to find the galasactl.properties file
- Extended the width of the token response dialog to prevent a horizontal scrollbar from appearing when the "Copy to clipboard" tooltip is visible
- Fixed vulnerabilities and updated Next.js to v14

The updated modals are shown below.

Token creation modal:
Screenshot 2023-12-04 at 11 07 00

Token response modal:
Screenshot 2023-12-04 at 11 07 22

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by CaroMac — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
