### PR TITLE
Added build log generation/uploading, updated java version

### PR DESCRIPTION
**Pull request by jaydee029**
For issue galasa-dev/projectmanagement#1965

### CODE REVIEW

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Review by jadecarino — CHANGES_REQUESTED** [review]
Great stuff - as with the other PRs, please can we change the upload artefacts to only happen on failure, and add the same into the PR builds, both with a retention period of 7 days

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by galasa-team** [comment]
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

**Comment by jaydee029** [comment]
> Great stuff - as with the other PRs, please can we change the upload artefacts to only happen on failure, and add the same into the PR builds, both with a retention period of 7 days

done

**Review by jadecarino — APPROVED** [review]
Approved for building

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
