### PR TITLE
Reduce Docker image size

### PR DESCRIPTION
**Pull request by eamansour**
To fix image push failures for https://github.com/galasa-dev/projectmanagement/issues/1647

- Updated Dockerfile to use a multi-stage build
- Enabled Next.js' output tracing to reduce image size and only copy files necessary to run the webui into the final image (see https://nextjs.org/docs/app/api-reference/next-config-js/output)
- Moved dex.proto into the `public` folder (will be removed once Dex-related implementation is moved into the auth service)

Building the image locally results in a 157MB image, originally 1.42GB:
Screenshot 2023-12-07 at 09 47 49

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-webui-pr-11-qp4wn for details. If you are unable to do so, please contact a member of the Galasa team.

**Review by KirbyKatcher — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
